---
- name: Setup SQL server
  hosts: host
  become: true

  roles:
    - dpredhat.ansible_role_mssql
    
  tasks:
    - name: Wait up to 30 seconds for server to become available after creation
      wait_for:
        port: 1433
        timeout: 30
    - name: Create new db
      include_role:
        name: dpredhat.ansible_role_mssql
        tasks_from: new_db
